### PR TITLE
Force subject video URLs to https

### LINKED ISSUE #123: "This Type of Video File is Not Supported"
Hi, several users complaint recently that videos are not playing. Message: "This Type of Video File is Not Supported". A particular problem seems to be the Edge browser of the current Windows version. Could you please look into that and maybe give advice (if cannot be solved)? Thanks!

### PR DESCRIPTION
**Pull request by astopy**
Closes #123

### CODE REVIEW

**Comment by shaunanoordin** [comment]
Apologies, but there appears to be an issue with this fix.

Issue: Attempting to access the Classifiy feature will show that the video has failed to load, with the error message "classify.cjsx?bb54:97 Uncaught TypeError: subject.location.standard.replace is not a function"

Analysis:
* The PR code refers to `subject.location.standard` and attempts to call a `.replace()` function on it.
* However, it appears that `subject.location.standard` is actually a generic `Object`, not a `String`, and doesn't have the `.replace` function
```
console.log(subject.location.standard) ==>
Object {mp4: "http://demo.zooniverse.org/chimps/subjects/54c7dbb769736d23bd010200/54c7dbb769736d23bd010200.mp4", webm: "http://demo.zooniverse.org/chimps/subjects/54c7dbb769736d23bd010200/54c7dbb769736d23bd010200.webm"}
```

Proposed Alternative:
Move the .replace() function further into the logic. In `classify.cjsx`...
```
212. source = if @isFirefox then @props.video.webm else @props.video.mp4
+++. source = source.replace('http://www.chimpandsee.org/', 'https://www.chimpandsee.org/')  #MS Edge compatibility
213. type = if @isFirefox then "video/webm" else "video/mp4"
```

Actions: **New commit incoming**

Note:
* I'm unsure if hardcoding the `https://www.chimpandsee.org/` string into the code is good for long-term maintainability; I'm wondering if the project is built to allow a more generic (e.g. config file-controlled) solution.
* Alternatively, I may just be overthinking this, as the MS edge error is _very specific_ to videos being served from http://www.chimpandsee.org.

**Comment by shaunanoordin** [comment]
EDIT: In the previous message, I said...
> Move the .replace() function further into the logic. In `classify.cjsx`...

...when I should have said...

> Move the .replace() function further into the logic. In `annotation/annotation.cjsx`...

**Comment by shaunanoordin** [comment]
@astopy I've just pushed a counter-proposal for the PR. Two things however:
1. I'm not addressing the hardcoded URL matter that I brought up. (That might spiral into a whole new config feature)
2. While the code is stable (i.e. everything compiles and runs fine on localhost), we can't really test that this specific change works until we deploy the code to https://www.chimpandsee.org. (Unless there's a way to mimic domains and cross-domain interactions; after all, Edge only goes cranky when it's https://www.chimpandsee.org trying to load http://www.chimpandsee.org videos.)

I'm happy to continue testing this when it goes into a live deploy to ensure compatibility across the browsers.

**Comment by astopy** [comment]
Oops, my bad on the TypeError. Thanks for fixing.

I think the hard-coded URL will be fine. The full URL is (unfortunately) stored in every subject record in Ouroboros anyway, so it's already not great for long-term.

I'll deploy this to live shortly so we can test before merging.

**Comment by shaunanoordin** [comment]
* `publisssh` updated to 1.1.0 to solve impossible-to-deploy problems.
* `https-subjects` branch deployed to https://www.chimpandsee.org/beta/ for testing
* **OK** on all tests!
  * Users can view videos
  * Users can continue making classifications
* Tested on Chrome51/FF46/Safari9
* Tested on IE11 + Win8

Status: **Self-verified**
@astopy , if there are no objections, I'm happy to merge & deploy to https://www.chimpandsee.org/

**Pull request merged**
